version: '3'

services:
  app:
    build: .
    ports:
      - 8081:80
    environment:
      - WEBPASSWORD_ORIGINS=http://127.0.0.1:8001,http://localhost:8001,http://localhost:8082,http://bs-local.com:8001
      - NEXTCLOUD_ADMIN_USER=admin
      - NEXTCLOUD_ADMIN_PASSWORD=admin
      - SQLITE_DATABASE=mydb
      - NEXTCLOUD_TRUSTED_DOMAINS=bs-local.com localhost 127.0.0.1
    volumes:
      - nextcloud:/var/www/html
      - ..:/var/www/html/custom_apps/qownnotesapi
      - ./nextcloud/certificates:/var/www/.nextcloud/certificates
      - ./owncloud/certificates:/var/www/.owncloud/certificates
      - ./nextcloud/sign-app.sh:/var/www/sign-app.sh
      - ./owncloud/sign-app.sh:/var/www/sign-app-owncloud.sh
      - ./qownnotesapi.config.php:/var/www/html/config/qownnotesapi.config.php

volumes:
  nextcloud:
