# Use `just <recipe>` to run a recipe
# https://just.systems/man/en/

# By default, run the `--choose` command
default:
    @just --choose

# Variables
# Try to use "docker compose" and fall back to "docker-compose" if not available

dockerComposeCommand := `docker compose > /dev/null && echo docker compose || echo docker-compose`

all: check-code test sign-app

build:
    {{ dockerComposeCommand }} build

fetch-db:
    {{ dockerComposeCommand }} run --rm app su -c "cp data/mydb.db apps/qownnotesapi" www-data

push-db:
    {{ dockerComposeCommand }} run --rm app su -c "cp apps/qownnotesapi/mydb.db* data" www-data

bash:
    {{ dockerComposeCommand }} run --rm app su -c "bash" www-data

bash-root:
    {{ dockerComposeCommand }} run --rm app bash

slim-shell:
    slim debug --target nextcloud-qownnotesapi-app-1

maintenance-mode-off:
    {{ dockerComposeCommand }} run --rm app su -c "./occ maintenance:mode --off" www-data

check-code:
    {{ dockerComposeCommand }} run --rm app su -c "./occ app:check-code qownnotesapi" www-data

sign-app:
    {{ dockerComposeCommand }} run --rm app ../sign-app.sh www-data

sign-app-owncloud:
    {{ dockerComposeCommand }} run --rm app ../sign-app-owncloud.sh

test:
    {{ dockerComposeCommand }} run --rm app su -c "cd apps/qownnotesapi && make test" www-data

show-log:
    {{ dockerComposeCommand }} run --rm app tail -f /var/www/html/data/nextcloud.log

remove-volumes:
    docker volume rm nextcloud-qownnotesapi_nextcloud
