version: "3"

services:
  owncloud:
    image: owncloud/server:10.8
    ports:
      - 8081:8080
    environment:
      - OWNCLOUD_DB_TYPE=sqlite
      - OWNCLOUD_DB_NAME=mydb
      - OWNCLOUD_ADMIN_USERNAME=admin
      - OWNCLOUD_ADMIN_PASSWORD=admin
      - OWNCLOUD_REDIS_ENABLED=false
    volumes:
      - owncloud:/mnt/data

volumes:
  owncloud:
